# Change these first
owner: LibreTurks # Your GitHub organization or username, where this repository lives
repo: manifests2 # The name of this repository

sites:
  - name: libreturks.dev - main
    url: https://libreturks.dev
    expectedStatusCodes:
      - 404
  - name: miniflux
    url: https://rss.libreturks.dev
  - name: keycloak
    url: https://auth.libreturks.dev
  - name: redmine
    url: https://redmine.libreturks.dev

status-website:
  cname: status.libreturks.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.libreturks.dev
  introTitle: "**status.libreturks.dev** is uptime monitor for libreturks pubnix, made with upptime."
  introMessage: LibreTurks Pubnix's Uptime Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
